name: Build Rom
description: Xem chi tiết
title: "Test: xxxxx"
labels: ["build"]
body:
  - type: markdown
    attributes:
      value: |
        Điền vào thông tin bên dưới để hoàn thành quá trình xây dựng rom
  - type: input
    attributes:
      label: Nhập liên kết
      description: Hãy điền liên kết tải rom vào đây
      placeholder: Url: 
    validations:
      required: false
