name: CI
on:
  workflow_dispatch:
  issues:
    types:
      - opened
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all
jobs:
  build:
    name: 'Xem quá trình'
    if: github.repository == 'Zelooooo/OS' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: "Load data ${{ github.event.issue.number }}"
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          #gh run cancel $GITHUB_RUN_NUMBER

          curl -L -H "Authorization: token $GH_TOKEN" -X POST "https://api.github.com/repos/Zelooooo/OS/actions/runs/$GITHUB_RUN_NUMBER/cancel"   

