name: CI
on:
  workflow_dispatch:
  issues:
    types:
      - opened
  push:
    paths:
      - '.github/workflows/Auto.yml'
      - 'test.sh'
permissions: write-all
jobs:
  build:
    name: 'Xem quá trình'
    if: github.repository == 'Zelooooo/OS' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: "Load data ${{ github.event.issue.number }}"
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          bash test.sh
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Add the very useful text file'
          add: 'Up/* --force'
          cwd: './'
          
