name: Build
on:
  workflow_dispatch:
  issues:
    types:
      - opened
permissions: write-all
jobs:
  build:
    name: 'Xem quá trình'
    if: github.repository == 'Zelooooo/OS' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Load data
        uses: actions/checkout@v3
      - name: Build
        run: |
          # kakathic
          . test.sh
      - name: Dán Link
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          labels: 'Hoàn thành'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 2
      - name: Dán Link 2
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 2
          body: |
            "NAME: ${{ env.NAMER }}<br/><br/>LINK DOWNLOAD: ${{ env.LINKROM }}<br/><br/>MD5: ${{ env.MD5 }}"   
          
