name: Build
on:
  workflow_dispatch:
  issues:
    types:
      - opened
permissions: write-all
jobs:
  build:
    name: 'Xem quá trình'
    if: github.repository == 'Zelooooo/OS' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Load data
        uses: actions/checkout@v3
      - name: Build
        run: |
          # kakathic
          . test.sh
      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Add some comments.
            你好 @${{ github.event.issue.user.login }}。巴拉巴拉。
          #emoji: '+1' or '+1,heart'


