name: Build
on:
  workflow_dispatch:
  issues:
    types:
      - opened
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all
jobs:
  build:
    name: 'Xem quá trình'
    if: github.repository == 'Zelooooo/OS' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Load data
        uses: actions/checkout@v3
      - name: Set Issues
        uses: zlus/action-extract-issues@1.0.0
        id: set_issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          match-reg: 'Test: xxxxx' 
          add-labels: enhancement   
          remove-labels: bug        
          add-comment: |            
            already fixed.
      - name: Log
        run: echo ${{ steps.set_issues.outputs.issues }}
      - name: lock-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 3
          labels: 'duplicate'
          body: test
          
