name: Build
on:
  workflow_dispatch:
  issues:
    types:
      - opened
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all
jobs:
  build:
    name: 'Xem quá trình'
    if: github.repository == 'Zelooooo/OS' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Load data
        uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              issue_number: 13,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              state_reason: 'completed',
              labels: ['Test2'],
              body: '👋 Thanks for reporting!'
            })
            github.rest.issues.removeLabel({
              issue_number: 13,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['Wait']
            })
