name: Build
on:
  workflow_dispatch:
  issues:
    types:
      - opened
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all
jobs:
  build:
    name: 'Xem quá trình'
    if: github.repository == 'Zelooooo/OS' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Load data
        uses: actions/checkout@v3

      - uses: lee-dohm/close-matching-issues@v2
        with:
          query: 'label:bug'
          token: ${{ secrets.GITHUB_TOKEN }}
