name: Build
on:
  workflow_dispatch:
  issues:
    types:
      - opened
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all
jobs:
  build:
    name: 'Xem quá trình'
    if: github.repository == 'Zelooooo/OS' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Load data
        uses: actions/checkout@v3
      - name: 'Tắt Issues'
        uses: actions/stale@v8
        with:
          run: env
