on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Close issues marked as fixed upon a release.
        uses: gcampbell/fixed-pending-release/@x.x.x
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: bug
          message: ":tada: This issue has" 
          
